name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: nightly-2021-12-09
  NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

jobs:
  release-sdk:
    runs-on: ubuntu-latest
    name: Release SDK on NPM
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          always-auth: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Yarn dependencies
        run: yarn install
      - name: Parse IDLs
        run: yarn idl:generate
      - run: yarn build
      - run: |
          echo 'npmAuthToken: "${NPM_AUTH_TOKEN}"' >> .yarnrc.yml
      - name: Publish
        run: yarn npm publish